CREATE TABLE `inventory_counts` (
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	`id` text PRIMARY KEY NOT NULL,
	`session_id` text NOT NULL,
	`product_id` text NOT NULL,
	`variant_id` text,
	`quantity_expected` text NOT NULL,
	`expected_loose_quantity` text NOT NULL,
	`quantity_counted` text NOT NULL,
	`counted_package_quantity` text NOT NULL,
	`counted_loose_quantity` text NOT NULL,
	`packaging_factor` integer,
	`quantity_difference` text NOT NULL,
	`unit_cost` text NOT NULL,
	`difference_value` text NOT NULL,
	`is_counted` integer NOT NULL,
	`counted_by_id` text,
	`counted_at` integer,
	`notes` text NOT NULL
);
--> statement-breakpoint
CREATE TABLE `inventory_sessions` (
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	`id` text PRIMARY KEY NOT NULL,
	`is_deleted` integer NOT NULL,
	`deleted_at` integer,
	`reference` text NOT NULL,
	`name` text NOT NULL,
	`warehouse_id` text NOT NULL,
	`scope_type` text NOT NULL,
	`status` text NOT NULL,
	`notes` text NOT NULL,
	`is_stock_locked` integer NOT NULL,
	`started_at` integer,
	`completed_at` integer,
	`validated_at` integer,
	`created_by_id` text,
	`validated_by_id` text,
	`total_expected_quantity` text NOT NULL,
	`total_counted_quantity` text NOT NULL,
	`total_difference_quantity` text NOT NULL,
	`total_difference_value` text NOT NULL
);
